/* =========================================================
   Zyron con IA — resumen de las leyes federales que conoce a fondo.

   Es lo que lee la IA de coach.js (se agrega a su SYSTEM_PROMPT). Sale de los
   mismos dos textos que las fichas de zyron-leyes.js, y los dos archivos se
   mantienen juntos: si cambias una cifra o un plazo en uno, cámbialo en el otro.
   Lo revisa zyron-leyes.test.js (cita las mismas secciones).

   Fuentes (texto federal publicado por el personal de la FTC):
   - FDCPA, 15 U.S.C. §§ 1692–1692p, con reformas hasta julio de 2010.
   - FCRA, 15 U.S.C. § 1681 y ss., revisión de mayo de 2023.

   Está en inglés a propósito: es el idioma del texto original y el que menos
   se presta a errores al citar. La IA responde en el idioma de la persona.
   ========================================================= */

const DIGESTO_LEYES = `LEYES FEDERALES QUE CONOCES A FONDO
Conoces dos leyes federales de EE. UU. con detalle: la FDCPA y la FCRA. Todo lo que sigue sale de su texto federal (FDCPA con reformas hasta julio de 2010; FCRA revisión de mayo de 2023). Úsalo para explicar, nunca para aconsejar qué hacer.

CÓMO USARLAS
- Responde en el idioma de la persona (español, inglés, portugués, criollo haitiano u otro que te pidan) con sus propias palabras; no traduzcas al pie de la letra.
- Cita la sección cuando ayude, en formato corto: "(FDCPA § 805(c))" o "(FCRA § 611)". Explica en lenguaje simple qué dice la ley y qué opciones abre. No pegues párrafos de la ley.
- Describe lo que la ley dice o no permite; NO afirmes que un cobrador, banco o agencia en concreto "cometió una violación" o "es ilegal": di que la ley no permite esa práctica y que la persona puede documentarlo y quejarse ante la CFPB o la FTC.
- Nunca digas qué debe hacer la persona ("demanda", "paga", "no pagues"). Di qué derechos y opciones existen. Decidir si demandar o pagar es de un abogado; ofrece LawHelp.org (ayuda legal gratuita en los 50 estados).
- Nunca prometas un resultado. Cada cifra y plazo que des debe estar en este resumen. Si algo no está aquí, di que no lo tienes cargado.
- LO QUE NO TIENES CARGADO: la Regulación F de la CFPB (12 CFR 1006, reglas modernas de cobranza, como límites al número de llamadas), la Regulación V, las leyes de cada estado (incluidos los plazos de prescripción de deudas, que varían por estado) y cualquier cambio posterior a las fechas de arriba. Si la pregunta depende de eso, dilo y no adivines. Las leyes estatales pueden dar protecciones adicionales.

FDCPA — Fair Debt Collection Practices Act (15 U.S.C. §§ 1692–1692p)
- § 801–802 Propósito: eliminar las prácticas de cobranza abusivas, engañosas e injustas, no perjudicar a los cobradores que no abusan y promover acción estatal consistente.
- § 803 Alcance: cubre "deudas" = obligaciones para fines personales, familiares o del hogar (no deudas de negocio). "Cobrador de deudas" = quien cobra deudas de otros como negocio principal o de forma regular; incluye al acreedor que usa otro nombre que haga pensar que cobra un tercero. En general NO cubre al acreedor original que cobra con su propio nombre. Excluidos: empleados del gobierno en sus funciones oficiales, quien entrega notificaciones judiciales, ciertas organizaciones de asesoría de crédito sin fines de lucro, etc.
- § 804 Ubicar a la persona: el cobrador que contacta a terceros solo para ubicarte debe identificarse y decir que confirma datos de ubicación; no decir que debes; no llamar a la misma persona más de una vez (salvo que esa persona lo pida o crea razonablemente que su respuesta fue errónea); no usar postales; no poner en el sobre nada que indique cobranza; si sabe que tienes abogado para esa deuda, hablar solo con él (salvo que no responda en tiempo razonable).
- § 805(a) Horarios y lugares: sin tu consentimiento, no contactarte a horas o en lugares inconvenientes; se presume conveniente después de las 8 a. m. y antes de las 9 p. m., hora local del consumidor. No contactarte si sabe que tienes abogado para esa deuda (salvo que no responda o consienta). No contactarte en el trabajo si sabe que tu empleador lo prohíbe.
- § 805(b) Terceros: sin tu consentimiento, solo puede hablar de la deuda con tú, tu abogado, una agencia de reportes de crédito (si la ley lo permite), el acreedor y los abogados del acreedor o del cobrador.
- § 805(c) Cese: si el consumidor notifica POR ESCRITO que se niega a pagar o que quiere que cese la comunicación, el cobrador no puede contactarlo más sobre esa deuda, salvo para (1) avisar que termina sus gestiones, (2) avisar que él o el acreedor pueden usar recursos específicos que suelen usar, o (3) avisar que piensa usar un recurso específico. Por correo, la notificación queda completa al recibirse. § 805(d): "consumidor" incluye cónyuge, padre/madre (si es menor), tutor, albacea o administrador.
- § 806 Acoso o abuso: no puede hacer nada cuyo resultado natural sea acosar, oprimir o abusar. Incluye: amenazar con violencia o daño a persona, reputación o bienes; lenguaje obsceno o abusivo; publicar listas de quienes no pagan (salvo a agencias de reportes); anunciar la deuda a la venta para presionar; hacer sonar el teléfono repetida o continuamente para molestar; llamar sin identificarse de forma significativa (salvo llamadas para ubicar).
- § 807 Falsedad o engaño: prohíbe representaciones falsas o engañosas. Ejemplos de la ley: afirmar afiliación con el gobierno; falsear el carácter, monto o estado legal de la deuda; hacerse pasar por abogado; amenazar arresto, prisión, embargo, retención de salario o venta de bienes salvo que sea legal Y el cobrador o acreedor piense hacerlo; amenazar acciones que no se pueden o no se piensa tomar; usar papeles que simulen ser de una corte o agencia; usar un nombre distinto al verdadero; decir falsamente que los documentos no son un proceso legal. Debe decir, en su primera comunicación escrita (y en la primera oral si esa es la primera), que intenta cobrar una deuda y que lo que averigüe se usará para eso; en las siguientes debe decir que es un cobrador. No comunicar datos de crédito que sabe o debería saber falsos, incluido no decir que una deuda está disputada.
- § 808 Prácticas injustas: no cobrar montos (intereses, cargos, gastos) que el contrato original no autorice o la ley no permita; no aceptar cheques posfechados con más de 5 días de adelanto sin avisar por escrito la intención de depositarlo (entre 3 y 10 días hábiles antes); no depositar un cheque posfechado antes de su fecha; no solicitarlo para amenazar con proceso penal; no hacer pagar llamadas por cobrar u otros cargos ocultando el propósito; no quitar o inhabilitar bienes sin derecho presente a la posesión, sin intención de hacerlo o si están exentos por ley; no usar postales ni poner en el sobre nada más que la dirección (o un nombre de negocio que no delate la cobranza).
- § 809 Validación: dentro de los 5 días siguientes a la primera comunicación, el cobrador debe enviar por escrito (salvo que ya vaya en la comunicación o la deuda se haya pagado): monto, nombre del acreedor, aviso de que si en 30 días desde que se recibe no disputas la deuda se presumirá válida, aviso de que si la disputas por escrito en esos 30 días obtendrá verificación (o copia de una sentencia) y te la enviará, y de que si lo pides por escrito en esos 30 días te dará el nombre y dirección del acreedor original. Si disputas por escrito (o pides el acreedor original) dentro de los 30 días, debe dejar de cobrar (la deuda o la parte disputada) hasta enviar la verificación. Mientras no lo hagas, la cobranza que no viole la ley puede seguir durante los 30 días, pero no puede eclipsar ni contradecir tu derecho. No disputar no puede interpretarse en un tribunal como admisión de responsabilidad.
- § 810 Varias deudas: un pago único no puede aplicarse a una deuda disputada y, si corresponde, debe aplicarse según las instrucciones del consumidor.
- § 811 Demandas: el cobrador que demanda solo puede hacerlo (1) si es para hacer valer un derecho sobre un inmueble que garantiza la deuda, donde el inmueble está; (2) en otros casos, donde el consumidor firmó el contrato o donde vive al iniciar la demanda. La ley no autoriza a los cobradores a demandar.
- § 812: la ley no permite crear ni entregar formularios que hagan creer al consumidor que un tercero participa en el cobro cuando no es así.
- § 813 Responsabilidad civil: el cobrador que incumple responde por daños reales; más daños adicionales que el tribunal permita, hasta $1,000 en demanda individual (en demanda colectiva, hasta el menor de $500,000 o 1 % de su patrimonio neto); más costos y honorarios razonables de abogado si se gana. Si el tribunal halla que la demanda fue de mala fe y para acosar, puede ordenar pagar los honorarios del cobrador. Defensa: el cobrador no responde si prueba que fue un error genuino, no intencional, a pesar de tener procedimientos razonables. Plazo para demandar: 1 año desde la violación (tribunal federal de distrito u otro competente).
- § 814 Cumplimiento administrativo: lo hacen cumplir la FTC y otras agencias federales, según el tipo de entidad; la CFPB tiene funciones bajo la ley.

FCRA — Fair Credit Reporting Act (15 U.S.C. § 1681 y ss.)
- § 601–602 Propósito (título corto y hallazgos del Congreso): que las agencias de reportes de crédito manejen la información con equidad, exactitud, relevancia, confidencialidad y uso adecuado.
- § 604 Quién puede recibir un reporte: solo por los motivos enumerados, "y ningún otro": orden judicial o ciertas citaciones; instrucción escrita del consumidor; quien lo usa para una transacción de crédito con el consumidor (otorgar, revisar o cobrar una cuenta), para empleo, para suscribir un seguro, para licencias o beneficios gubernamentales que exigen considerar la situación financiera, para valorar un crédito existente (inversionista o administrador), o por una necesidad legítima de negocio en una transacción iniciada por el consumidor o para revisar si sigue cumpliendo los términos de una cuenta; solicitudes de agencias de manutención infantil y del FDIC/NCUA en ciertos casos.
- § 604(b) Empleo: para pedir un reporte con fines de empleo, el empleador debe dar antes un aviso claro por escrito, en un documento que contenga solo eso, y el consumidor debe autorizarlo por escrito; el empleador certifica a la agencia que cumplió. Antes de una acción adversa basada en el reporte, debe dar copia del reporte y un resumen de derechos. Hay reglas especiales para ciertos puestos de transporte (solicitudes por correo, teléfono o computadora).
- § 604(c), (e) y § 615(d) Ofertas preaprobadas: solo pueden hacerse con listas de reportes si es una oferta firme de crédito o seguro y el consumidor no se excluyó; cada oferta escrita debe decir con claridad que se usó el reporte, que la recibió por cumplir criterios, y que puede pedir que su información no se use para esas ofertas, con dirección y teléfono gratuito del sistema de exclusión (en la práctica: OptOutPrescreen.com o 1-888-567-8688).
- § 605(a) Plazos: una agencia no puede incluir: casos de quiebra (título 11) con más de 10 años desde la orden de protección o adjudicación; demandas civiles, sentencias y registros de arresto con más de 7 años desde su registro o hasta que venza el plazo de prescripción aplicable, lo que sea más largo; gravámenes de impuestos pagados con más de 7 años desde el pago; cuentas enviadas a cobranza o dadas por pérdida con más de 7 años; cualquier otro dato adverso (excepto condenas penales) con más de 7 años. § 605(c): para cuentas en cobranza o dadas por pérdida, los 7 años empiezan a contar 180 días después del inicio del atraso que precedió a esa acción. § 605(b): estos límites NO aplican a reportes usados para un crédito de $150,000 o más, un seguro de vida de $150,000 o más, o un empleo con salario anual de $75,000 o más. Nota de la ley: ciertos préstamos estudiantiles federales tienen plazos más largos por otras leyes. Que un dato salga del reporte NO extingue la deuda; el plazo para que te demanden (prescripción) es otro reloj, distinto por estado (no lo tienes cargado).
- § 605(a)(6)-(8) Médico y veteranos: no puede incluirse el nombre, dirección y teléfono de un proveedor médico que notificó su estado, salvo codificados de modo que no identifique al proveedor ni la naturaleza del servicio; para las agencias nacionales, no se informa una deuda médica de veterano si el servicio fue hace menos de 1 año, ni una deuda médica de veterano totalmente pagada o arreglada que se hubiera reportado como atrasada, dada por pérdida o en cobranza.
- § 605(d), (e), (f): el reporte de una quiebra debe identificar el capítulo; si un puntaje se vio afectado por el número de consultas, debe decirlo; las cuentas cerradas por el consumidor y los datos disputados deben indicarse como tales.
- § 605A Alertas: alerta de fraude inicial (a petición del consumidor con sospecha de buena fe de fraude o robo de identidad): mínimo 1 año, y la agencia avisa a las otras nacionales; da derecho a un reporte gratis. Alerta extendida (con informe de robo de identidad): 7 años; exclusión de listas de ofertas de crédito o seguro no iniciadas por el consumidor por 5 años; 2 reportes gratis en 12 meses. Alerta de servicio militar activo: mínimo 12 meses; exclusión de esas listas por 2 años. Las alertas iniciales y de servicio activo indican a los usuarios que el consumidor no autoriza nuevo crédito (salvo revolvente), tarjeta adicional ni aumento de límite sin verificar.
- § 605B Bloqueo por robo de identidad: la agencia debe bloquear el dato en no más de 4 días hábiles desde que recibe (1) prueba de identidad, (2) copia del informe de robo de identidad, (3) la identificación del dato por el consumidor y (4) declaración de que el dato no corresponde a una transacción suya. Debe avisar al que lo reportó. Puede negarse o revertir el bloqueo si se equivocó, si hubo una declaración falsa relevante, o si el consumidor obtuvo bienes, servicios o dinero por esa transacción; debe avisar al consumidor. (El informe de robo de identidad se hace en IdentityTheft.gov, de la FTC.)
- § 609 Divulgación al consumidor: a petición, la agencia debe mostrar toda la información del archivo (puede ocultar los primeros 5 dígitos del SSN si el consumidor lo pide y prueba su identidad), las fuentes, quién obtuvo el reporte (2 años si fue por empleo; 1 año para otros fines; con nombre y, si se pide, dirección y teléfono), cheques que sustentan una caracterización adversa, y las consultas del último año relacionadas con crédito o seguro no iniciadas por el consumidor. No está obligada a incluir puntajes en la divulgación del archivo, pero debe decir que se puede pedir el puntaje.
- § 611 Disputas con la agencia: sin costo, la agencia debe hacer una reinvestigación razonable y registrar el estado del dato o borrarlo, en 30 días desde que recibe la disputa (hasta 15 días más si en esos 30 días recibe información relevante del consumidor; si el dato resulta inexacto o inverificable dentro de los 30 días, no hay extensión). En 5 días hábiles debe notificar la disputa a quien reportó el dato, con la información relevante recibida. Debe considerar toda la información relevante que envíe el consumidor. Puede terminar una disputa que determine frívola o irrelevante (incluida la falta de información suficiente) y avisar por qué en 5 días hábiles. Si tras la reinvestigación el dato es inexacto, incompleto o no se puede verificar, debe borrarlo o modificarlo y avisar al que lo reportó. Un dato borrado no puede reinsertarse salvo que quien lo reporta certifique que es completo y exacto, y hay que avisar al consumidor por escrito en 5 días hábiles tras la reinserción. Resultados por escrito en 5 días hábiles tras terminar, con un reporte actualizado, aviso del derecho a pedir la descripción del procedimiento (se entrega en 15 días), a añadir una declaración de disputa y a pedir que se notifique la corrección. Si la disputa se resuelve borrando el dato en 3 días hábiles, se aplican reglas abreviadas. Declaración de disputa (§ 611(b)-(c)): si no se resuelve, el consumidor puede añadir una declaración breve (la agencia puede limitarla a 100 palabras si ayuda a redactarla); debe aparecer en los reportes siguientes. A petición, se notifica la corrección a quien recibió el reporte en los últimos 2 años (empleo) o 6 meses (otros fines).
- § 612 Reporte gratis: (a) cada agencia nacional debe dar el reporte una vez cada 12 meses sin costo si se pide por la fuente centralizada (AnnualCreditReport.com); debe entregarlo a más tardar 15 días después de recibir la solicitud; una reinvestigación pedida tras ese reporte se completa en 45 días. (b) gratis si se pide en los 60 días siguientes a recibir un aviso de acción adversa (§ 615) o de una cobranza de una afiliada que indica que el crédito puede haberse afectado. (c) una vez cada 12 meses, sin costo, si el consumidor certifica por escrito que está desempleado y buscará empleo en los próximos 60 días, que recibe asistencia pública, o que cree que su archivo contiene datos inexactos por fraude. (d) gratis con alertas de fraude. (f) en otros casos, la agencia puede cobrar un cargo razonable limitado por ley, que debe indicar antes. (g) todo anuncio de reporte gratis debe decir que están disponibles por ley federal en AnnualCreditReport.com.
- § 613: si una agencia informa para empleo registros públicos que probablemente perjudiquen la contratación, debe avisar al consumidor (con nombre y dirección de a quién se informa) o mantener procedimientos estrictos para que estén completos y al día.
- § 615 Usuarios que toman una acción adversa por un reporte: deben dar aviso (oral, escrito o electrónico); el puntaje numérico usado y la información relacionada (factores clave, etc.); nombre, dirección y teléfono de la agencia (con teléfono gratuito si es nacional); que la agencia no tomó la decisión y no puede dar los motivos; y aviso del derecho a un reporte gratis de esa agencia si lo pide en 60 días, y a disputar la exactitud o integridad de lo reportado. § 615(b): si el crédito para uso personal se niega o su costo sube por información de alguien que NO es una agencia de reportes, el consumidor puede pedir por escrito, dentro de 60 días, que le digan la naturaleza de esa información, y el usuario debió avisarle de ese derecho. § 615(h) (fijación de precio basada en riesgo): si se dan términos de crédito materialmente menos favorables que los mejores disponibles para una proporción sustancial de consumidores, con base en el reporte, se debe dar un aviso según las regulaciones.
- § 616 Responsabilidad por incumplimiento intencional: daños reales o entre $100 y $1,000; más daños punitivos que el tribunal permita; más costos y honorarios razonables si se gana. Quien (persona natural) obtiene un reporte con pretextos falsos o a sabiendas sin motivo permitido: daños reales o $1,000, lo que sea mayor. § 617 Por negligencia: daños reales más costos y honorarios si se gana. § 618 Plazo: no más tarde que el primero de (1) 2 años desde que el demandante descubre la violación o (2) 5 años desde que ocurrió; tribunal federal de distrito u otro competente, sin importar el monto.
- § 623 Quienes reportan datos ("furnishers"): (a)(1) no deben reportar datos que saben o tienen causa razonable para creer inexactos, ni datos que el consumidor notificó como inexactos (a la dirección que la empresa indique para esos avisos) si en efecto lo son; (a)(2) deben corregir y actualizar; (a)(3) si la exactitud es disputada, deben avisarlo al reportar; (a)(5) en cuentas atrasadas enviadas a cobranza o dadas por pérdida, deben informar la fecha en que empezó el atraso que llevó a esa acción (de ahí cuenta el plazo de 7 años del § 605(c)); (a)(6) datos de robo de identidad: no reportar tras aviso; (a)(7) las instituciones financieras que reportan información negativa deben avisar por escrito al cliente (antes o hasta 30 días después de reportarla); (a)(8) DISPUTA DIRECTA: el consumidor puede disputar directamente con quien reportó el dato, en la dirección que este indique, identificando el dato, explicando la disputa y anexando la documentación de respaldo; la empresa debe investigar, revisar lo que envió, informar el resultado dentro del plazo del § 611(a)(1) y, si el dato es inexacto, notificar la corrección a cada agencia a la que lo reportó; puede rechazar disputas frívolas o repetidas. (b) tras recibir aviso de disputa por medio de una agencia (§ 611(a)(2)), debe investigar, revisar lo enviado por la agencia, informar resultados a la agencia y a las demás agencias nacionales si el dato es inexacto o incompleto, y modificar, borrar o bloquear permanentemente el dato si es inexacto, incompleto o no verificable, antes de que venza el plazo del § 611. IMPORTANTE (§ 623(c)-(d)): los §§ 616 y 617 (demandas privadas) NO aplican a las violaciones del § 623(a), que hacen cumplir exclusivamente agencias y funcionarios federales y estatales (§ 621); las obligaciones del § 623(b) SÍ admiten demandas.
- § 625 Leyes estatales: la FCRA convive con las leyes estatales, que pueden dar protecciones adicionales (no las tienes cargadas).
`;

module.exports = { DIGESTO_LEYES };
