const {verificarFirmaWebhook,supa}=require('./lib/pagos-stripe');const H={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'},out=(s,b)=>({statusCode:s,headers:H,body:JSON.stringify(b)});
async function patch(table,query,data){return supa(`${table}?${query}`,{method:'PATCH',body:JSON.stringify(data)});}
async function dispatch(ev){const o=ev.data.object;
 if(ev.type==='checkout.session.completed')return patch('pagos',`stripe_checkout_session_id=eq.${o.id}`,{estado:'pagado',stripe_payment_intent_id:o.payment_intent,actualizado_en:new Date().toISOString()});
 if(ev.type==='payment_intent.payment_failed')return patch('pagos',`stripe_payment_intent_id=eq.${o.id}`,{estado:'fallido',actualizado_en:new Date().toISOString()});
 if(ev.type==='charge.refunded'){const rs=await (await supa(`pagos?stripe_payment_intent_id=eq.${o.payment_intent}&select=*`)).json(),p=rs[0];if(!p)return;return patch('pagos',`id=eq.${p.id}`,{estado:o.amount_refunded>=p.monto_centavos?'reembolsado':'reembolsado_parcial',actualizado_en:new Date().toISOString()});}
 if(ev.type==='charge.dispute.created'||ev.type==='charge.dispute.closed'){const rs=await (await supa(`pagos?stripe_payment_intent_id=eq.${o.payment_intent||o.charge}&select=*`)).json(),p=rs[0];if(!p)return;return supa('disputas?on_conflict=stripe_dispute_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({pago_id:p.id,stripe_dispute_id:o.id,estado:ev.type.endsWith('created')?'necesita_respuesta':(o.status==='won'?'ganada':'perdida'),monto_centavos:o.amount})});}
 if(ev.type.startsWith('customer.subscription.')){const estado=ev.type.endsWith('deleted')?'cancelada':o.status==='past_due'?'pago_pendiente':'activa';return supa('suscripciones?on_conflict=stripe_subscription_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({user_id:o.metadata&&o.metadata.user_id,stripe_subscription_id:o.id,plan:(o.items&&o.items.data&&o.items.data[0]&&o.items.data[0].price.id)||'stripe',estado})});}
 if(ev.type==='invoice.payment_failed')return patch('suscripciones',`stripe_subscription_id=eq.${o.subscription}`,{estado:'pago_pendiente',actualizado_en:new Date().toISOString()}); return 'ignorado';}
exports.handler=async e=>{if(e.httpMethod!=='POST')return out(405,{error:'Método no permitido.'});const raw=e.body||'',sig=e.headers['stripe-signature']||e.headers['Stripe-Signature'];if(!verificarFirmaWebhook(raw,sig,process.env.STRIPE_WEBHOOK_SECRET))return out(400,{error:'Firma inválida.'});let ev;try{ev=JSON.parse(raw)}catch(_){return out(400,{error:'Firma inválida.'})}const ins=await supa('eventos_pago_webhook',{method:'POST',body:JSON.stringify({stripe_event_id:ev.id,tipo:ev.type,estado_procesamiento:'ok'})});if(ins.status===409)return out(200,{recibido:true,duplicado:true});if(!ins.ok)return out(500,{error:'No pudimos registrar el evento.'});try{const state=await dispatch(ev);await patch('eventos_pago_webhook',`stripe_event_id=eq.${ev.id}`,{estado_procesamiento:state==='ignorado'?'ignorado':'ok',procesado_en:new Date().toISOString()});return out(200,{recibido:true});}catch(err){await patch('eventos_pago_webhook',`stripe_event_id=eq.${ev.id}`,{estado_procesamiento:'error',error_detalle:String(err.message).slice(0,500),procesado_en:new Date().toISOString()});return out(500,{error:'No pudimos procesar el evento.'});}};
