const crypto = require("node:crypto");
function formEncode(obj, prefijo) { const partes=[]; for(const clave of Object.keys(obj||{})){const valor=obj[clave]; if(valor==null)continue; const nombre=prefijo?prefijo+"["+clave+"]":clave; partes.push(typeof valor==="object"?formEncode(valor,nombre):encodeURIComponent(nombre)+"="+encodeURIComponent(String(valor)));} return partes.join("&"); }
async function stripe(ruta,cuerpo,metodo,opciones={}) { const res=await fetch("https://api.stripe.com/v1/"+ruta,{method:metodo||"POST",headers:{Authorization:"Bearer "+process.env.STRIPE_SECRET_KEY,"Content-Type":"application/x-www-form-urlencoded",...(opciones.idempotencyKey?{"Idempotency-Key":opciones.idempotencyKey}:{})},body:cuerpo?formEncode(cuerpo):undefined}); const datos=await res.json(); if(!res.ok){const err=new Error((datos.error&&datos.error.message)||"Stripe devolvió un error.");err.stripe=true;throw err;}return datos; }
async function esAdmin(accessToken){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_ANON_KEY;if(!url||!key||!accessToken)return false;try{const r=await fetch(url.replace(/\/$/,"")+"/auth/v1/user",{headers:{Authorization:"Bearer "+accessToken,apikey:key}});if(!r.ok)return false;const u=await r.json();return !!(u.app_metadata&&u.app_metadata.is_admin);}catch(_){return false;}}
function verificarFirmaWebhook(rawBody,header,secret){if(!header||!secret)return false;const m=Object.fromEntries(header.split(",").map(x=>x.split("=")).filter(x=>x.length===2));if(!m.t||!m.v1)return false;const expected=crypto.createHmac("sha256",secret).update(m.t+"."+rawBody).digest("hex");try{return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(m.v1));}catch(_){return false;}}
function idempotencyKey(...parts){return parts.map(x=>String(x).replace(/[^a-zA-Z0-9:_-]/g,"_")).join(":");}
async function usuarioDelToken(token){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_ANON_KEY;if(!url||!key||!token)return null;const r=await fetch(url.replace(/\/$/,"")+"/auth/v1/user",{headers:{Authorization:"Bearer "+token,apikey:key}}).catch(()=>null);return r&&r.ok?await r.json():null;}
function supa(path,opts={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;return fetch(url.replace(/\/$/,"")+"/rest/v1/"+path,{...opts,headers:{apikey:key,Authorization:"Bearer "+key,"Content-Type":"application/json",Prefer:opts.prefer||"return=representation",...(opts.headers||{})}});}
module.exports={formEncode,stripe,esAdmin,verificarFirmaWebhook,idempotencyKey,usuarioDelToken,supa};
